name: Merge a feature branch to develop upon passing CI

# Controls when the workflow will run
on:
  push:
    branches:
      - 'feature/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          java-package: 'jdk'

      # Building maven
      - name: mvn build
        run: mvn -B package

      # Running integration tests together with jacoco
      - name: check tests
        run: mvn -B jacoco:prepare-agent test jacoco:report

      # Report
      - name: test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            target/site/jacoco/*

      # Spotbug
      - name: static analysis
        run: mvn spotbugs:check

      #Checkstyle
      - name: linting
        run: mvn checkstyle:check
